spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  jwt:
    access:
      expiration: 3600000
    refresh:
      expiration: 2419200000
    secret: ${SPRING_JWT_SECRET}
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9099/eureka